-- Psst core schema.
--
-- Clients may only read through row-level security (RLS) and write through the
-- functions below. Every function derives the caller from auth.uid(); no function
-- accepts a user ID for "who am I". Errors use PostgREST's PTxxx codes, so they
-- reach the client as HTTP status xxx with a machine-readable message.

create schema if not exists private;
revoke all on schema private from public;

-- Effects ---------------------------------------------------------------------

create table public.effects (
    id text primary key,
    title text not null,
    is_free boolean not null default true,
    sort_order int not null
);

insert into public.effects (id, title, is_free, sort_order) values
    ('psst', 'Psst', true, 1),
    ('squeeze', 'Squeeze', true, 2),
    ('oi', 'Oi', true, 3),
    ('duck', 'Duck', true, 4);

-- People and connections -------------------------------------------------------

create table public.profiles (
    id uuid primary key references auth.users (id) on delete cascade,
    display_name text not null check (char_length(btrim(display_name)) between 1 and 40),
    created_at timestamptz not null default now()
);

-- One row per mutually accepted pair, stored with user_a < user_b.
create table public.connections (
    id uuid primary key default gen_random_uuid(),
    user_a uuid not null references public.profiles (id) on delete cascade,
    user_b uuid not null references public.profiles (id) on delete cascade,
    a_favorite text not null default 'psst' references public.effects (id),
    b_favorite text not null default 'psst' references public.effects (id),
    created_at timestamptz not null default now(),
    check (user_a < user_b),
    unique (user_a, user_b)
);
create index connections_user_b_idx on public.connections (user_b);

create table public.invites (
    id uuid primary key default gen_random_uuid(),
    code text not null unique,
    inviter_id uuid not null references public.profiles (id) on delete cascade,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null default now() + interval '7 days',
    accepted_by uuid references public.profiles (id) on delete set null,
    accepted_at timestamptz,
    revoked_at timestamptz
);
create index invites_inviter_idx on public.invites (inviter_id);

create table public.blocks (
    blocker_id uuid not null references public.profiles (id) on delete cascade,
    blocked_id uuid not null references public.profiles (id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (blocker_id, blocked_id),
    check (blocker_id <> blocked_id)
);
create index blocks_blocked_idx on public.blocks (blocked_id);

-- Signals ----------------------------------------------------------------------

create table public.signal_events (
    -- Generated by the sending device and reused on retry: the deduplication key.
    id uuid primary key,
    connection_id uuid not null references public.connections (id) on delete cascade,
    sender_id uuid not null references public.profiles (id) on delete cascade,
    recipient_id uuid not null references public.profiles (id) on delete cascade,
    effect_id text not null references public.effects (id),
    -- Server time. The only timestamp used for ordering and reciprocal timing.
    created_at timestamptz not null default now(),
    -- Set only when the recipient's app reports it displayed the signal.
    seen_at timestamptz,
    -- APNs acceptance is not device delivery; this never implies receipt.
    push_status text not null default 'pending'
        check (push_status in ('pending', 'accepted', 'failed', 'no_devices'))
);
create index signal_events_recipient_idx on public.signal_events (recipient_id, created_at desc);
create index signal_events_sender_idx on public.signal_events (sender_id, created_at desc);
create index signal_events_connection_idx on public.signal_events (connection_id, created_at desc);

create table public.device_tokens (
    token text primary key,
    user_id uuid not null references public.profiles (id) on delete cascade,
    environment text not null check (environment in ('sandbox', 'production')),
    updated_at timestamptz not null default now()
);
create index device_tokens_user_idx on public.device_tokens (user_id);

-- Row-level security: read-only, own data only ----------------------------------

alter table public.effects enable row level security;
alter table public.profiles enable row level security;
alter table public.connections enable row level security;
alter table public.invites enable row level security;
alter table public.blocks enable row level security;
alter table public.signal_events enable row level security;
alter table public.device_tokens enable row level security;

revoke all on public.effects, public.profiles, public.connections, public.invites,
    public.blocks, public.signal_events, public.device_tokens from anon, authenticated;
grant select on public.effects, public.profiles, public.connections, public.invites,
    public.blocks, public.signal_events to authenticated;

create policy effects_read on public.effects for select to authenticated using (true);

create policy profiles_read on public.profiles for select to authenticated using (
    id = auth.uid()
    or exists (
        select 1 from public.connections c
        where (c.user_a = auth.uid() and c.user_b = profiles.id)
           or (c.user_b = auth.uid() and c.user_a = profiles.id)
    )
);

create policy connections_read on public.connections for select to authenticated
    using (auth.uid() in (user_a, user_b));

create policy invites_read on public.invites for select to authenticated
    using (inviter_id = auth.uid());

create policy blocks_read on public.blocks for select to authenticated
    using (blocker_id = auth.uid());

create policy signal_events_read on public.signal_events for select to authenticated
    using (auth.uid() in (sender_id, recipient_id));

-- Helpers ----------------------------------------------------------------------

create function private.require_user() returns uuid
language plpgsql stable set search_path = '' as $$
declare
    me uuid := auth.uid();
begin
    if me is null then
        raise exception 'not_authenticated' using errcode = 'PT401';
    end if;
    return me;
end;
$$;

create function private.is_blocked(a uuid, b uuid) returns boolean
language sql stable set search_path = '' as $$
    select exists (
        select 1 from public.blocks
        where (blocker_id = a and blocked_id = b) or (blocker_id = b and blocked_id = a)
    );
$$;

create function private.normalize_code(raw text) returns text
language sql immutable set search_path = '' as $$
    select upper(regexp_replace(coalesce(raw, ''), '[^A-Za-z0-9]', '', 'g'));
$$;

-- 8 characters from an alphabet without look-alikes (no 0/O, 1/I/L, U).
create function private.new_invite_code() returns text
language plpgsql volatile set search_path = '' as $$
declare
    alphabet constant text := 'ABCDEFGHJKMNPQRSTVWXYZ23456789';
    bytes bytea := uuid_send(gen_random_uuid()) || uuid_send(gen_random_uuid());
    result text := '';
begin
    for i in 0..7 loop
        result := result || substr(alphabet, 1 + (get_byte(bytes, i) % 30), 1);
    end loop;
    return result;
end;
$$;

-- Profile ----------------------------------------------------------------------

create function public.set_display_name(p_name text) returns void
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
    trimmed text := btrim(coalesce(p_name, ''));
begin
    if char_length(trimmed) not between 1 and 40 then
        raise exception 'invalid_name' using errcode = 'PT422';
    end if;
    insert into public.profiles (id, display_name) values (me, trimmed)
    on conflict (id) do update set display_name = excluded.display_name;
end;
$$;

-- Invites ----------------------------------------------------------------------

create function public.create_invite() returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
    new_code text;
    inv public.invites;
begin
    if not exists (select 1 from public.profiles where id = me) then
        raise exception 'profile_required' using errcode = 'PT409';
    end if;
    if (select count(*) from public.invites
        where inviter_id = me and accepted_at is null and revoked_at is null
          and expires_at > now()) >= 5 then
        raise exception 'too_many_invites' using errcode = 'PT429';
    end if;
    loop
        new_code := private.new_invite_code();
        begin
            insert into public.invites (code, inviter_id) values (new_code, me) returning * into inv;
            exit;
        exception when unique_violation then
            -- Code collision: try another.
        end;
    end loop;
    return jsonb_build_object('code', inv.code, 'expires_at', inv.expires_at);
end;
$$;

create function public.revoke_invite(p_code text) returns void
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
begin
    update public.invites set revoked_at = now()
    where code = private.normalize_code(p_code) and inviter_id = me
      and accepted_at is null and revoked_at is null;
    if not found then
        raise exception 'invite_invalid' using errcode = 'PT404';
    end if;
end;
$$;

-- Shared by preview and accept. Returns the status as seen by the caller.
create function private.invite_status(inv public.invites, me uuid) returns text
language plpgsql stable set search_path = '' as $$
begin
    if inv.id is null then return 'invalid'; end if;
    if inv.inviter_id = me then return 'own'; end if;
    if private.is_blocked(me, inv.inviter_id) then return 'invalid'; end if;
    if exists (select 1 from public.connections
               where user_a = least(me, inv.inviter_id) and user_b = greatest(me, inv.inviter_id)) then
        return 'already_connected';
    end if;
    if inv.accepted_at is not null then return 'used'; end if;
    if inv.revoked_at is not null then return 'revoked'; end if;
    if inv.expires_at <= now() then return 'expired'; end if;
    return 'pending';
end;
$$;

create function public.preview_invite(p_code text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
    inv public.invites;
    status text;
begin
    select * into inv from public.invites where code = private.normalize_code(p_code);
    status := private.invite_status(inv, me);
    return jsonb_build_object(
        'status', status,
        'inviter_name', case when status in ('pending', 'already_connected')
            then (select display_name from public.profiles where id = inv.inviter_id) end
    );
end;
$$;

create function public.accept_invite(p_code text) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
    inv public.invites;
    status text;
    conn_id uuid;
begin
    if not exists (select 1 from public.profiles where id = me) then
        raise exception 'profile_required' using errcode = 'PT409';
    end if;
    select * into inv from public.invites where code = private.normalize_code(p_code) for update;
    status := private.invite_status(inv, me);

    if status = 'pending' then
        insert into public.connections (user_a, user_b)
        values (least(me, inv.inviter_id), greatest(me, inv.inviter_id))
        returning id into conn_id;
        update public.invites set accepted_by = me, accepted_at = now() where id = inv.id;
        status := 'accepted';
    elsif status = 'already_connected' then
        select id into conn_id from public.connections
        where user_a = least(me, inv.inviter_id) and user_b = greatest(me, inv.inviter_id);
    else
        raise exception 'invite_%', status using errcode = case status
            when 'invalid' then 'PT404'
            when 'own' then 'PT409'
            when 'used' then 'PT409'
            else 'PT410' end;
    end if;
    return jsonb_build_object('status', status, 'connection_id', conn_id);
end;
$$;

-- Connections ------------------------------------------------------------------

create function public.list_connections() returns table (
    connection_id uuid,
    other_id uuid,
    other_name text,
    my_favorite text,
    last_event_id uuid,
    last_from_me boolean,
    last_effect text,
    last_created_at timestamptz,
    last_seen_at timestamptz,
    unseen_count int
)
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
begin
    return query
    select c.id,
           o.id,
           o.display_name,
           case when c.user_a = me then c.a_favorite else c.b_favorite end,
           e.id,
           e.sender_id = me,
           e.effect_id,
           e.created_at,
           e.seen_at,
           (select count(*)::int from public.signal_events u
            where u.connection_id = c.id and u.recipient_id = me and u.seen_at is null)
    from public.connections c
    join public.profiles o on o.id = case when c.user_a = me then c.user_b else c.user_a end
    left join lateral (
        select * from public.signal_events s
        where s.connection_id = c.id
        order by s.created_at desc, s.id
        limit 1
    ) e on true
    where me in (c.user_a, c.user_b)
    order by o.display_name, c.id;
end;
$$;

create function public.set_favorite(p_connection_id uuid, p_effect_id text) returns void
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
begin
    if not exists (select 1 from public.effects where id = p_effect_id and is_free) then
        raise exception 'effect_unavailable' using errcode = 'PT403';
    end if;
    update public.connections set
        a_favorite = case when user_a = me then p_effect_id else a_favorite end,
        b_favorite = case when user_b = me then p_effect_id else b_favorite end
    where id = p_connection_id and me in (user_a, user_b);
    if not found then
        raise exception 'not_connected' using errcode = 'PT403';
    end if;
end;
$$;

create function public.remove_connection(p_connection_id uuid) returns void
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
begin
    delete from public.connections where id = p_connection_id and me in (user_a, user_b);
    if not found then
        raise exception 'not_connected' using errcode = 'PT403';
    end if;
end;
$$;

-- Blocking removes the connection. The blocked person is not told; their sends
-- fail the same way as for any removed connection.
create function public.block_user(p_user_id uuid) returns void
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
begin
    if p_user_id is null or p_user_id = me
       or not exists (select 1 from public.profiles where id = p_user_id) then
        raise exception 'invalid_user' using errcode = 'PT422';
    end if;
    insert into public.blocks (blocker_id, blocked_id) values (me, p_user_id)
    on conflict do nothing;
    delete from public.connections
    where user_a = least(me, p_user_id) and user_b = greatest(me, p_user_id);
end;
$$;

create function public.unblock_user(p_user_id uuid) returns void
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
begin
    delete from public.blocks where blocker_id = me and blocked_id = p_user_id;
end;
$$;

create function public.list_blocked() returns table (user_id uuid, display_name text, blocked_at timestamptz)
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
begin
    return query
    select b.blocked_id, p.display_name, b.created_at
    from public.blocks b join public.profiles p on p.id = b.blocked_id
    where b.blocker_id = me
    order by b.created_at desc;
end;
$$;

-- Signals ----------------------------------------------------------------------

create function public.send_signal(p_event_id uuid, p_connection_id uuid, p_effect_id text)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
    c public.connections;
    other uuid;
    ev public.signal_events;
begin
    if p_event_id is null then
        raise exception 'invalid_event_id' using errcode = 'PT422';
    end if;

    -- Idempotent retry: the same ID from the same sender returns the original.
    select * into ev from public.signal_events where id = p_event_id;
    if found then
        if ev.sender_id <> me then
            raise exception 'invalid_event_id' using errcode = 'PT422';
        end if;
        return jsonb_build_object('id', ev.id, 'created_at', ev.created_at,
            'push_status', ev.push_status, 'duplicate', true);
    end if;

    select * into c from public.connections where id = p_connection_id and me in (user_a, user_b);
    if not found then
        raise exception 'not_connected' using errcode = 'PT403';
    end if;
    other := case when c.user_a = me then c.user_b else c.user_a end;
    if private.is_blocked(me, other) then
        raise exception 'not_connected' using errcode = 'PT403';
    end if;

    if not exists (select 1 from public.effects where id = p_effect_id and is_free) then
        raise exception 'effect_unavailable' using errcode = 'PT403';
    end if;

    -- Pacing: at most 10 per minute to one person and 30 per minute overall.
    if (select count(*) from public.signal_events
        where sender_id = me and recipient_id = other
          and created_at > now() - interval '1 minute') >= 10
       or (select count(*) from public.signal_events
           where sender_id = me and created_at > now() - interval '1 minute') >= 30 then
        raise exception 'rate_limited' using errcode = 'PT429';
    end if;

    insert into public.signal_events (id, connection_id, sender_id, recipient_id, effect_id)
    values (p_event_id, c.id, me, other, p_effect_id)
    on conflict (id) do nothing
    returning * into ev;

    if ev.id is null then
        -- A concurrent request with the same ID won the insert.
        select * into ev from public.signal_events where id = p_event_id;
        if ev.sender_id <> me then
            raise exception 'invalid_event_id' using errcode = 'PT422';
        end if;
        return jsonb_build_object('id', ev.id, 'created_at', ev.created_at,
            'push_status', ev.push_status, 'duplicate', true);
    end if;

    return jsonb_build_object('id', ev.id, 'created_at', ev.created_at,
        'push_status', ev.push_status, 'duplicate', false);
end;
$$;

-- Called by the recipient's app after it actually displayed the signal.
create function public.ack_signals(p_event_ids uuid[]) returns int
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
    n int;
begin
    update public.signal_events set seen_at = now()
    where id = any (p_event_ids) and recipient_id = me and seen_at is null;
    get diagnostics n = row_count;
    return n;
end;
$$;

create function public.list_unseen() returns table (
    id uuid, connection_id uuid, sender_id uuid, sender_name text, effect_id text, created_at timestamptz
)
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
begin
    return query
    select s.id, s.connection_id, s.sender_id, p.display_name, s.effect_id, s.created_at
    from public.signal_events s join public.profiles p on p.id = s.sender_id
    where s.recipient_id = me and s.seen_at is null
    order by s.created_at desc
    limit 50;
end;
$$;

-- Device tokens ----------------------------------------------------------------

-- A token belongs to whoever registered it last; reinstalling or switching
-- accounts on a device moves it rather than duplicating it.
create function public.register_device_token(p_token text, p_environment text) returns void
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
begin
    if p_token !~ '^[0-9a-f]{64,200}$' or p_environment not in ('sandbox', 'production') then
        raise exception 'invalid_token' using errcode = 'PT422';
    end if;
    if not exists (select 1 from public.profiles where id = me) then
        raise exception 'profile_required' using errcode = 'PT409';
    end if;
    insert into public.device_tokens (token, user_id, environment) values (p_token, me, p_environment)
    on conflict (token) do update
        set user_id = excluded.user_id, environment = excluded.environment, updated_at = now();
    -- Keep the 10 most recent tokens per person.
    delete from public.device_tokens
    where user_id = me and token not in (
        select token from public.device_tokens where user_id = me order by updated_at desc limit 10);
end;
$$;

create function public.unregister_device_token(p_token text) returns void
language plpgsql security definer set search_path = '' as $$
declare
    me uuid := private.require_user();
begin
    delete from public.device_tokens where token = p_token and user_id = me;
end;
$$;

-- Server-only: used by the send-signal function with the service role --------

create function public.push_targets(p_event_id uuid) returns jsonb
language sql security definer set search_path = '' as $$
    select jsonb_build_object(
        'event_id', s.id,
        'connection_id', s.connection_id,
        'effect_id', s.effect_id,
        'push_status', s.push_status,
        'sender_name', p.display_name,
        'tokens', coalesce((select jsonb_agg(jsonb_build_object('token', t.token, 'environment', t.environment))
                            from public.device_tokens t where t.user_id = s.recipient_id), '[]'::jsonb))
    from public.signal_events s join public.profiles p on p.id = s.sender_id
    where s.id = p_event_id;
$$;

create function public.record_push_result(p_event_id uuid, p_status text, p_invalid_tokens text[])
returns void
language plpgsql security definer set search_path = '' as $$
begin
    update public.signal_events set push_status = p_status where id = p_event_id;
    delete from public.device_tokens where token = any (coalesce(p_invalid_tokens, '{}'));
end;
$$;

-- Retention: signals kept 30 days, finished invites 30 days after they end.
create function private.purge_expired() returns void
language sql security definer set search_path = '' as $$
    delete from public.signal_events where created_at < now() - interval '30 days';
    delete from public.invites
    where coalesce(accepted_at, revoked_at, expires_at) < now() - interval '30 days';
$$;

-- Function privileges ----------------------------------------------------------

revoke execute on all functions in schema public from public, anon, authenticated;
revoke execute on all functions in schema private from public, anon, authenticated;

grant execute on function
    public.set_display_name(text),
    public.create_invite(),
    public.revoke_invite(text),
    public.preview_invite(text),
    public.accept_invite(text),
    public.list_connections(),
    public.set_favorite(uuid, text),
    public.remove_connection(uuid),
    public.block_user(uuid),
    public.unblock_user(uuid),
    public.list_blocked(),
    public.send_signal(uuid, uuid, text),
    public.ack_signals(uuid[]),
    public.list_unseen(),
    public.register_device_token(text, text),
    public.unregister_device_token(text)
to authenticated;

grant execute on function
    public.push_targets(uuid),
    public.record_push_result(uuid, text, text[])
to service_role;
